services:
  contact-us-nginx:
    volumes:
      - ./nginx/contact-us-local.crt:/etc/nginx/certs/contact-us-local.crt:ro
      - ./nginx/contact-us-local.key:/etc/nginx/certs/contact-us-local.key:ro
  contact-us-django:
    # For hot reloading in development.
    volumes:
      - ./django/src:/src
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
